version: "3"

services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    ports:
      - 3000:3000
    volumes:
      - ./client:/client
      - /client/node_modules

    command: npm start
    restart: always
    tty: true
    networks:
      - webappnetwork
    depends_on:
      - server

  server:
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    ports:
      - 3001:3001
      - 9229:9229
    command: npm run dev
    env_file: ./server/.env
    volumes:
      - ./server:/server
    restart: always
    tty: true
    networks:
      - webappnetwork
    depends_on:
      - db

  db:
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: test_db

    command: "mysqld --init-file /data/application/init.sql"
    volumes:
      - mariadbb-data:/var/lib/mysql
      - ./db_init/init.sql:/data/application/init.sql

    tty: true
    ports:
      - 33306:3306
    networks:
      - webappnetwork

networks:
  webappnetwork:
    driver: bridge

volumes:
  mariadbb-data:
